### ISSUE TITLE
Missing HTML and title tag

### ISSUE THREAD

**Issue by codekendo** [thyrgle/kelleybioinfo#28]
Consider using this boiler plate for the base html template.

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

**Comment by thyrgle** [comment]
Note to self: Need to add `{% block title %}` Blah. `{% enblock %}` to all the templates... Again, integration test to enforce? Might be tricky since `base.html` and `auth.html` don't need one, but their children do...
